Backup/MIMS/Controllers/LoginsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using MIMS.Models;
using AlfasiWeb.Properties;
using MIMS.Security;
using MIMS.Util;
using Dinota.Core.Extensions;
using Dinota.Core.Specification;
using Dinota.Security;
using Dinota.Security.Group;
using Dinota.Security.Login;

namespace MIMS.Controllers
{
    public class LoginsController : BaseController
    {

        private readonly LoginService _loginService;

        private readonly GroupService _groupService;

        public LoginsController(LoginService loginService, GroupService groupService, ISecurityContext securityContext)
            : base(securityContext)
        {
            _loginService = loginService;
            _groupService = groupService;
        }

        //
        // GET: /Groups/
        [DinotaAuthorize(FunctionalAreas.UserGroups, SetPermission = true)]
        [OutputCache(Duration = 0)]
        public ActionResult Groups(int userId, ListModel listModel)
        {
            var filter = _loginService.GetDefaultSpecification();
            filter = filter.And(login => login.Id == userId);

            _loginService.Include(login => login.Groups);

            var theLogin = _loginService.GetBy(filter);

            ViewData[ViewDataKeys.Login] = theLogin;

            if (listModel == null)
            {
                listModel = new ListModel { Column = "Name" };
            }
            else if (listModel.Column.IsNullOrEmpty())
            {
                listModel.Column = "Name";
            }

            ViewData[ViewDataKeys.List] = _groupService.GetPagination(listModel);

            return PartialView("Groups",listModel);
        }

        //
        // GET: /RemoveFromGroup/
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult RemoveFromGroup(int loginId, int groupId)
        {
            var filter = _loginService.GetDefaultSpecification();
            filter = filter.And(login => login.Id == loginId);

            _loginService.Include(login => login.Groups);

            try
            {
                var theLogin = _loginService.GetBy(filter);

                if (theLogin.Groups.Any(group => group.Id == groupId))
                {
                    theLogin.Groups.Remove(theLogin.Groups.First(group => group.Id == groupId));

                    DataContext.SaveChanges();
                }

                return
                    Content(GetAjaxHelper().ActionLink("Add", "AddToGroup", new { loginId, groupId, rand = new Random().Next() },
                                                       new AjaxOptions()
                                                       {
                                                           OnFailure = "serverError();",
                                                           UpdateTargetId = "grp-" + groupId,
                                                           LoadingElementId = "ajax-loading"
                                                       }).ToString());
            }
            catch (Exception)
            {
                return Content(Resources.UnableToProcessRequest);
            }
        }

        //
        // GET: /AddToGroup/
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult AddToGroup(int loginId, int groupId)
        {
            var filter = _loginService.GetDefaultSpecification();
            filter = filter.And(login => login.Id == loginId);

            _loginService.Include(login => login.Groups);

            try
            {
                var theLogin = _loginService.GetBy(filter);

                if (!theLogin.Groups.Any(group => group.Id == groupId))
                {
                    var groupFilter = _groupService.GetDefaultSpecification();
                    groupFilter = groupFilter.And(group => group.Id == groupId);

                    var theGroup = _groupService.GetBy(groupFilter);

                    theLogin.Groups.Add(theGroup);

                    DataContext.SaveChanges();
                }

                return
                    Content(GetAjaxHelper().ActionLink("Remove", "RemoveFromGroup", new { loginId, groupId, rand = new Random().Next() },
                                                       new AjaxOptions()
                                                       {
                                                           OnFailure = "serverError();",
                                                           UpdateTargetId = "grp-" + groupId,
                                                           LoadingElementId = "ajax-loading"
                                                       }).ToString());
            }
            catch (Exception)
            {
                return Content(Resources.UnableToProcessRequest);
            }
        }

        protected HtmlHelper GetHtmlHelper()
        {
            var viewContext = new ViewContext(ControllerContext, new WebFormView(ControllerContext, "fake"), ViewData,
                                              TempData, System.IO.TextWriter.Null);
            return new HtmlHelper(viewContext, new ViewPage());
        }

        protected AjaxHelper GetAjaxHelper()
        {
            var viewContext = new ViewContext(ControllerContext, new WebFormView(ControllerContext, "fake"), ViewData,
                                              TempData, System.IO.TextWriter.Null);
            return new AjaxHelper(viewContext, new ViewPage());
        }

    }
}

Backup/MIMS/Controllers/UsersController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using MIMS.Helpers;
using MIMS.Models;
using MIMS.Security;
using AlfasiWeb.Util;
using Dinota.Core.Specification;
using Dinota.Domain;
using Dinota.Domain.AdminUser;
using Dinota.Domain.User;
using Dinota.Security;
using Dinota.Security.Crypto;
using Dinota.Models;
using Dinota.Domain.PageObject;
using Dinota.Domain.UserPermission;
using Dinota.Domain.UserType;
using System.Collections.Generic;
using Dinota.Domain.Division;

namespace MIMS.Controllers
{
    [ExternalUserRedirectAttribute]
    public class UsersController : BaseController
    {
        private readonly UserBaseService _userService;
        private readonly AdminUserService _adminUserService;
        private readonly UserPermissionService _userPermissionService;
        private readonly PageObjectService _pageObjectService;
        private readonly UserAccountService _userAccountService;
        private readonly UserTypeService _userTypeService;
        private readonly DivisionService _divisionService;
        private readonly ICryptoProvider _cryptoProvider;

        public UsersController(UserBaseService userService, DivisionService divisionService, UserTypeService userTypeService, PageObjectService pageObjectService, UserPermissionService userPermissionService, AdminUserService adminUserService, UserAccountService userAccountService,
           IDomainContext domainContext, ICryptoProvider cryptoProvider)
            : base(domainContext)
        {
            _userService = userService;
            _adminUserService = adminUserService;           
            _userAccountService = userAccountService;
            _cryptoProvider = cryptoProvider;
            _userPermissionService = userPermissionService;
            _pageObjectService = pageObjectService;
            _userTypeService = userTypeService;
            _divisionService = divisionService;
        }

        [DinotaAuthorize(FunctionalAreas.Users, SetPermission = true)]
        public ActionResult Index(UserSearchModel userSearchModel, byte typeenum = 1)
        {
            if (string.IsNullOrWhiteSpace(userSearchModel.Column))
            {
                userSearchModel.Column = "UserName";
            }

            TempData[ViewDataKeys.UserTypeEnum] = typeenum;

            LoadDataWithCurrentUser(typeenum, userSearchModel);

            return  View(userSearchModel);
            
        }

        [DinotaAuthorize(FunctionalAreas.Users, SetPermission = true)]
        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult LoadUserList(UserSearchModel userSearchModel, byte typeenum)
        {

            if (string.IsNullOrWhiteSpace(userSearchModel.Column))
            {
                userSearchModel.Column = "UserName";
            }

            TempData[ViewDataKeys.UserTypeEnum] = typeenum;

            LoadDataWithCurrentUser(typeenum, userSearchModel);

            return PartialView(userSearchModel);
        }

        private void LoadDataWithCurrentUser(byte typeenum, UserSearchModel userSearchModel)
        {
            if (typeenum == 1)
            {
                var filter = _userAccountService.GetDefaultSpecification();
               // ViewData[ViewDataKeys.List] = _userAccountService.GetPagination(filter, userSearchModel);
            }
            if (typeenum == 2)
            {
               

            }

            if (typeenum == 3)
            {
                

            }

            if (typeenum == 4)
            {
            
            }

            if (typeenum == 5)
            {
              

            }

            if (typeenum == 6)
            {
             

            }

            ViewData[ViewDataKeys.CurrentUser] = MembershipUser.UserName;
        }

        [OutputCache(Duration = 0)]
        [DinotaAuthorize(FunctionalAreas.Users, Writable = true)]
        public ActionResult Create( )
        {
            return PartialView();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [DinotaAuthorize(FunctionalAreas.Users, Writable = true)]
        public ActionResult Create(RegisterModel registerModel)
        {
           
            if (ModelState.IsValid)
            {
                byte usertypeenum = (byte)TempData[ViewDataKeys.UserTypeEnum];
                try
                {
                    switch (usertypeenum)
                    {
                        case 1:
                            CreateUserAccount(registerModel, _userAccountService);
                            break;
                        case 2:
                           
                            break;
                        case 3:
                            
                            break;
                        case 4:
                          
                            break;
                        case 5:
                          
                            break;
                        case 6:
                            
                            break;
                    }
                    
                    //ViewData[ViewDataKeys.Message] = new SuccessMessage(string.Format(Resources.EntityCreateSuccess, "Record"));

                    return RedirectToAction("Index", "users", new { typeenum = usertypeenum });
                 
                    
                }
                catch (System.Data.DataException de)
                {
                    ExceptionTranslator.Trnaslate(de, ModelState);
                    ViewData[ViewDataKeys.Message] = new FailMessage(string.Format(ModelState.LastOrDefault().Value.Errors[0].ErrorMessage, "Record"));
                    return RedirectToAction("Index", "users", new { typeenum = usertypeenum });
                }
            }

            return PartialView();
        }

        private void CreateUserAccount(RegisterModel registerModel,object service)
        {
            if(service is UserAccountService)
            {
              var user = ((UserAccountService)service).Create();
              user.UserName = registerModel.UserName;
              user.Name = registerModel.Name;
              user.Telephone1 = registerModel.Telephone1;
              user.Email = registerModel.Email;
              user.PasswordHash = _cryptoProvider.HashPassword(registerModel.Password);
              ((UserAccountService)service).Add(user); 
            }

            DataContext.SaveChanges();
        }


        [OutputCache(Duration = 0)]
        [DinotaAuthorize(FunctionalAreas.Users, Writable = true)]
        public ActionResult Edit(int id)
        {
            var filter = _userService.GetDefaultSpecification();
            filter = filter.And(user => user.Id == id);

            var theUser = _userService.GetBy(filter);
            
            return PartialView(theUser);
        }

        [HttpPost]
        [DinotaAuthorize(FunctionalAreas.Users, Writable = true)]
        public ActionResult Edit(int id, FormCollection collection)
        {

            byte usertypeenum = (byte)TempData[ViewDataKeys.UserTypeEnum];
            try
            {
                var filter = _userService.GetDefaultSpecification();
                filter = filter.And(user => user.Id == id);

                var theUser = _userService.GetBy(filter);

                if (theUser == null)
                {
                    return RedirectToAction("Index","users");
                }

                UpdateModel(theUser);

                DataContext.SaveChanges();

               // ViewData[ViewDataKeys.Message] = new SuccessMessage(string.Format(Resources.EntityEditSuccess, "Record"));

                return RedirectToAction("Index", "users", new { typeenum = usertypeenum });
           
            }
            catch (System.Data.DataException de)
            {
                ExceptionTranslator.Trnaslate(de, ModelState);
                ViewData[ViewDataKeys.Message] = new FailMessage(string.Format(ModelState.LastOrDefault().Value.Errors[0].ErrorMessage, "Record"));
                return RedirectToAction("Index", "users", new { typeenum = usertypeenum });
             
            }
        }

        //
        // GET: /Groups/Delete/5
        [OutputCache(Duration = 0)]
        [DinotaAuthorize(FunctionalAreas.Users, Writable = true)]
        public ActionResult Delete(int id)
        {
            var user = _userService.GetByKey(id);
            TempData[ViewDataKeys.UserId] = id;
            var resetModel = new ResetPasswordModel { UserName = user.UserName };
            return PartialView("Delete", resetModel);
        }

        [HttpPost]
        [OutputCache(Duration = 0)]
        [DinotaAuthorize(FunctionalAreas.Users, Writable = true)]
        public ActionResult DeleteConfirm(int id)
        {
            try
            {
                byte usertypeenum = (byte)TempData[ViewDataKeys.UserTypeEnum];

                var filter = _userService.GetDefaultSpecification();
                filter = filter.And(user => user.Id == id);

                var theUser = _userService.GetBy(filter);

                if (theUser == null)
                {
                    //ViewData[ViewDataKeys.Message] = new FailMessage(string.Format(Resources.EntityNotFound, "Record"));

                    return RedirectToAction("Index");
                }
                _userService.Delete(theUser);
                DataContext.SaveChanges();

                //ViewData[ViewDataKeys.Message] = new SuccessMessage(string.Format(Resources.EntityDeleteSuccess, "Record"));

                Cache.Remove(CacheKeys.Suppliers);
                Cache.Remove(CacheKeys.Fabricators);
                Cache.Remove(CacheKeys.Erectors);
                Cache.Remove(CacheKeys.Transporters);

                return RedirectToAction("Index", "users", new { typeenum = usertypeenum });
             
            }

Backup/MIMS/Views/Users/Delete.cshtml
@using AlfasiWeb
@using AlfasiWeb.Helpers
@using AlfasiWeb.Models
@model ResetPasswordModel
@{
    TempData.Keep(ViewDataKeys.UserTypeEnum);
    object test = TempData[ViewDataKeys.UserTypeEnum];
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    
@using (Html.BeginForm("DeleteConfirm", "Users", new { id = (int)TempData[ViewDataKeys.UserId] }, FormMethod.Post))
{
    <div>Are you sure you want to delete  @Model.UserName?</div>
    <input type="submit" class="btn" value="Yes"  />
    <input type="button" class="btn" value="No" onclick="CloseDeleteDialog();" />
}

Backup/MIMS/Views/Users/Details.cshtml
@using AlfasiWeb
@using AlfasiWeb.Util
@using Dinota.Security
@using MvcContrib.UI.Pager
@model Dinota.Domain.User.UserBase
@using AlfasiWeb.Helpers
@{
    TempData.Keep(ViewDataKeys.UserTypeEnum);
    string userTitle = null;
    var userTypeEnum = (byte)TempData[ViewDataKeys.UserTypeEnum];
    var isDoFab = Model.IsFabUser;

    switch (userTypeEnum)
    {
        case 1:
            userTitle = "User";
            break;
        case 2:
            userTitle = "Project Manager";
            break;
        case 3:
            userTitle = "Supplier";
            break;
        case 4:
            userTitle = "Fabricator";
            break;
        case 5:
            userTitle = "Transporter";
            break;
        case 6:
            userTitle = "Erector";
            break;
    }
    var attribs = new Dictionary<string, object> { { "class", "input-xlarge" } };

    RolePermission rolePermission = TempData.ContainsKey(ViewDataKeys.DetailPermission)
                                      ? (RolePermission)TempData[ViewDataKeys.DetailPermission]
                                      : new RolePermission(false);
    
}
<div id="group_table" class="login_bk">
    <div class="content-bk">
        <h3 id="form_head">
            @userTitle Details</h3>
        @using (Html.BeginForm())
        {
            <br />
            <div id="detail-handler">
                <div id="new" class="row-fluid">
                    <div class="span4 pull-left">
                        <dl class="dl-horizontal">
                            <dt>@Html.DetailLabelFor(model => model.UserName)</dt>
                            <dd>
                                @Html.DetailFor(model => model.UserName, 80)</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div id="detail-handler">
                <div id="new" class="row-fluid">
                    <div class="span4 pull-left">
                        <dl class="dl-horizontal">
                            <dt>@Html.DetailLabelFor(model => model.Name)</dt>
                            <dd>
                                @Html.DetailFor(model => model.Name, 80)</dd>
                        </dl>
                    </div>
                </div>
            </div>
            if (userTypeEnum == 3)
            {
            <div id="detail-handler">
                <div id="new" class="row-fluid">
                    <div class="span4 pull-left">
                        <dl class="dl-horizontal">
                            <dt>@Html.DetailLabelFor(model => model.IsFabUser)</dt>
                            <dd>
                                @Html.CheckBoxFor(model => model.IsFabUser,new {@disabled = true})</dd>
                        </dl>
                    </div>
                </div>
            </div>
            }   
            <div id="detail-handler">
                <div id="new" class="row-fluid">
                    <div class="span4 pull-left">
                        <dl class="dl-horizontal">
                            <dt>@Html.DetailLabelFor(model => model.Telephone1)</dt>
                            <dd>
                                @Html.DetailFor(model => model.Telephone1, 80)</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div id="detail-handler">
                <div id="new" class="row-fluid">
                    <div class="span4 pull-left">
                        <dl class="dl-horizontal">
                            <dt>@Html.DetailLabelFor(model => model.Email)</dt>
                            <dd>
                                @Html.DetailFor(model => model.Email, 80)</dd>
                        </dl>
                    </div>
                </div>
            </div>
            <div class="link_bar">
                @Ajax.ActionLink("Back to List", "LoadUserList", "users", new { typeenum = (byte)TempData[ViewDataKeys.UserTypeEnum] }, new AjaxOptions() { OnFailure = "serverError();", UpdateTargetId = "divUserBase" }, new { @class = "link-btn" })
                @if ((!isDoFab || userTypeEnum != 4) && rolePermission.CanEdit)
                {
                   @Ajax.ActionLink("| Edit", "Edit", "Users", new {id = Model.Id}, new AjaxOptions {OnFailure = "serverError();", UpdateTargetId = "divUserBase"}, new {@class = "link-btn"})
                }
            </div>
        }
    </div>
</div>

Backup/MIMS/Views/Users/EditMember.cshtml
@using MIMS
@using MIMS.Helpers
@using Dinota.Security
@using AlfasiWeb.Models
@using Dinota.Domain.User
@model UserAccount
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}

<div id="content_wrapper" class="card-overlay">
    <div id="header_wrapper" class="header-md ">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <header id="header">
                        <h1>Edit User Account</h1>
                        <ol class="breadcrumb">
                            <li><a href="@Url.Content("~/Home/Index")">Dashboard</a></li>
                            <li><a href="javascript:void(0)">User Account</a></li>
                        </ol>
                    </header>
                </div>
            </div>
        </div>
    </div>
    <div id="content" class="container">

        <div class="content-body">
            <div class="row">
                <div class="col-xs-12">
                    <div class="card">
                        <header class="card-heading ">
                            <h2 class="card-title">Edit User Account</h2>
                        </header>
                        <div class="card-body">
                            @Html.Message()
                            @using (Html.BeginForm("EditMember", "Users", new { id=Model.Id}, FormMethod.Post, new { @class = "form-horizontal" }))
                            {
                                @Html.Partial("_CreateEdit", Model)
                                        
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

Backup/MIMS/Views/Users/LoadUserList.cshtml
@model UserSearchModel
@using AlfasiWeb
@using AlfasiWeb.Helpers
@using AlfasiWeb.Models
@using AlfasiWeb.Properties
@using AlfasiWeb.Util
@using Dinota.Domain.User
@using Dinota.Security

@Scripts.Render("~/bundles/TableSorter")
@Scripts.Render("~/bundles/scrollbar")

@Html.GetDeleteDiv()
@Html.GetBootsrapDiv("ResetPasswordPopUp-Element", "ResetPassword", "Reset password")
@Html.GetBootsrapDiv("GroupsPopUp-Element", "Groups", "Groups")
@{
    string userTitle = null;
    TempData.Keep(ViewDataKeys.UserTypeEnum);
    var usertypeenum = (byte) TempData[ViewDataKeys.UserTypeEnum];

    switch (@usertypeenum)
    {
        case 1:
        userTitle = "User";
        break;
        case 2:
        userTitle = "Project Manager";
        break;
        case 3:
        userTitle = "Supplier";
        break;
        case 4:
        userTitle = "Fabricator";
        break;
        case 5:
        userTitle = "Transporter";
        break;
        case 6:
        userTitle = "Erector";
        break;
    }
}

<div id="group_table" class="login_bk">
    @Html.Message()
    <div class="content-bk">
        <div id="form_head">
            <h3>@userTitle</h3>
        </div>
        <br/>
        <div >
            @{

                var rolePermission = ViewData.ContainsKey(ViewDataKeys.Permission)
                                                    ? (RolePermission) ViewData[ViewDataKeys.Permission]
                                                    : new RolePermission(false);

                TempData[ViewDataKeys.DetailPermission] = rolePermission;
                
                var currentUser = (string) ViewData[ViewDataKeys.CurrentUser];

                var users = ((IEnumerable<UserBase>) ViewData[ViewDataKeys.List]).ToList();
                Html.Custom().Grid(users, "ManageUsers", true).Sort(Model.GetGridSortOptions())
                    .Columns(column =>
                                 {
                                     column.For(user => Ajax.ActionLink(user.UserName, "Details", "Users", new {id = user.Id}, new AjaxOptions {OnFailure = "serverError();", UpdateTargetId = "divUserBase"}, new { @class = "btn-link pull-left"})).Named("Username").Sortable(false).ShowFilter(true);
                                     column.For(user => user.Name).Named("Name").Sortable(false).ShowFilter(true);
                                     column.For(user => Html.FuzzyDate(user.LastActiveDate)).Named("Last Active Date").SortColumnName("LastActiveDate").Sortable(false);

                                     //if (usertypeenum == 1 || usertypeenum == 2)
                                     //{
                                     //    column.For(user => Ajax.BoostrapedPopUpActionLink("Groups", "Groups", "Logins", new {userId = user.Id}, new AjaxOptions {UpdateTargetId = "GroupsPopUp-Element", OnSuccess = "javascript:BoostrapView('Groups');"}, "Groups")).Visible(rolePermission.CanEdit).Attributes(a => new Dictionary<string, object> {{"class", "span g_links"}}).Sortable(false);
                                     //}
                                     //else
                                     //{
                                     //    column.For(user => "").Sortable(false);
                                     //}

                                     if (rolePermission.CanEdit && usertypeenum != 4)
                                    {
                                        column.For(user => Ajax.BoostrapedPopUpActionLink("Groups", "Groups", "Logins", new {userId = user.Id}, new AjaxOptions {UpdateTargetId = "GroupsPopUp-Element", OnSuccess = "javascript:BoostrapView('Groups');"}, "Groups")).Visible(rolePermission.CanEdit).Attributes(a => new Dictionary<string, object> {{"class", "span g_links"}}).Sortable(false);
                                        column.For(user => Ajax.BoostrapedPopUpActionLink("Reset password", "ResetPassword", "Users", new {id = user.Id}, new AjaxOptions {UpdateTargetId = "ResetPasswordPopUp-Element", OnSuccess = "javascript:BoostrapView('ResetPassword');"}, "Reset Password")).Visible(rolePermission.CanEdit).Attributes(a => new Dictionary<string, object> {{"class", "span g_links"}}).Sortable(false);
                                        column.For(user => Ajax.ActionLink("Edit", "Edit", "Users", new {id = user.Id}, new AjaxOptions {OnFailure = "serverError();", UpdateTargetId = "divUserBase"})).Visible(rolePermission.CanEdit).Attributes(a => new Dictionary<string, object> {{"class", "span g_links"}}).Sortable(false);
                                        column.For(user => Ajax.BoostrapedDeletePopUpActionLink(user)).Encode(false).CellCondition(u => !(u.UserName == currentUser || u.UserName == Resources.AliasAdminUser)).Visible(rolePermission.CanEdit).Attributes(a => new Dictionary<string, object> {{"class", "span g_links"}}).Sortable(false);
                                    }
                                    else if (rolePermission.CanEdit && usertypeenum == 4)
                                    {
                                       column.For(user => Ajax.BoostrapedPopUpActionLink("Groups", "Groups", "Logins", new {userId = user.Id}, new AjaxOptions {UpdateTargetId = "GroupsPopUp-Element", OnSuccess = "javascript:BoostrapView('Groups');"}, "Groups")).Visible(rolePermission.CanEdit).Attributes(a => new Dictionary<string, object> {{"class", "span g_links"}}).Sortable(false).Encode(false).CellCondition(u => !u.IsFabUser);
                                        column.For(user => Ajax.BoostrapedPopUpActionLink("Reset password", "ResetPassword", "Users", new { id = user.Id }, new AjaxOptions { UpdateTargetId = "ResetPasswordPopUp-Element", OnSuccess = "javascript:BoostrapView('ResetPassword');" }, "Reset Password")).Visible(rolePermission.CanEdit).Attributes(a => new Dictionary<string, object> { { "class", "span g_links" } }).Sortable(false).Encode(false).CellCondition(u => !u.IsFabUser);
                                        column.For(user => Ajax.ActionLink("Edit", "Edit", "Users", new { id = user.Id }, new AjaxOptions { OnFailure = "serverError();", UpdateTargetId = "divUserBase" })).Visible(rolePermission.CanEdit).Attributes(a => new Dictionary<string, object> { { "class", "span g_links" } }).Sortable(false).Encode(false).CellCondition(u => !u.IsFabUser);
                                        column.For(user => Ajax.BoostrapedDeletePopUpActionLink(user)).Encode(false).CellCondition(u => !(u.UserName == currentUser || u.UserName == Resources.AliasAdminUser)).Visible(rolePermission.CanEdit).Attributes(a => new Dictionary<string, object> { { "class", "span g_links" } }).Sortable(false).Encode(false).CellCondition(u => !u.IsFabUser);
                                    }
                                    else
                                    {
                                        column.For(user => "").Sortable(false);
                                        column.For(user => "").Sortable(false);
                                        column.For(user => "").Sortable(false);
                                        column.For(user => "").Sortable(false);
                                    }
                                 }).Render();

            }
        </div>
        <div class="link_bar">
            @if (@rolePermission.CanAdd)
            {
                @Ajax.ActionLink("New " + userTitle, "Create", "users", new AjaxOptions {OnFailure = "serverError();", UpdateTargetId = "divUserBase"}, new {@class = "btn-link pull-right"})
            }
        </div>
    </div>
</div>

<script src="@Url.Content("~/Scripts/custom/commonscript.js")" type="text/javascript"> </script>
<script type="text/javascript">

    var dTable = null;

    if ($.browser.msie && $.browser.version == 9) {
        //left it if we can come up with a fix
    } else {
        setTimeout(function() {
            $(".dataTables_scrollBody").mCustomScrollbar({
                    theme: "dark-thick",
                    advanced: {
                        updateOnBrowserResize: true,
                        updateOnContentResize: true
                    }
                });
        }, 50);
    }

    $(document).ready(function () {

        SetFilterColumnCount(2);

        dTable = $('#ManageUsers').dataTable({
            "aoColumns": [null, null, null, { "bSortable": false }, { "bSortable": false }, { "bSortable": false }, { "bSortable": false}],
            "bPaginate": false,
            "bLengthChange": false,
            "bFilter": false,
            "bSort": true,
            "bInfo": false,
            "sScrollY": "300px",
            "bAutoWidth": false,
            "bScrollCollapse": false,
            "bSortCellsTop": true,
            "bRetrieve": true
        });

        $(window).bind('resize', CustomResize);

    });

    var update_size = function () {

        dTable.css({ width: dTable.parent().width() });
        dTable.fnAdjustColumnSizing();

    };

    function CustomResize() {

        $(window).unbind('resize');
        
        clearTimeout(window.refresh_size);
        window.refresh_size = setTimeout(function () {
            update_size();
        }, 50);
        
        $(window).bind('resize', CustomResize);

    }

</script>