MIMS/Controllers/BaseController.cs
using System;
using System.IO;
using System.Web;
using System.Web.Caching;
using System.Web.Mvc;
using System.Web.Routing;
using MIMS.Models;
using MIMS.Security;
using MIMS.Util;
using Dinota.Core.Data;
using Dinota.Core.Specification;
using Dinota.Domain.Filter;
using Dinota.Security.Membership;

namespace MIMS.Controllers
{
    [HandleError]
    public class BaseController : Controller
    {
        protected const int DefaultPageSize = 20;

        protected const int DialogPageSize = 5;
        protected ExceptionTranslator ExceptionTranslator = new ExceptionTranslator();

        public IMembershipService MembershipService { get; set; }

        protected BaseController()
        {

        }

        protected BaseController(IDataContext dataContext)
        {
            DataContext = dataContext;
        }

        protected IDataContext DataContext { get; set; }

        protected Cache Cache { get { return ControllerContext.HttpContext.Cache; } }

        protected override void Initialize(RequestContext requestContext)
        {
            if (MembershipService == null)
            {
                MembershipService = new AccountMembershipService();
            }
            base.Initialize(requestContext);
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            if (filterContext.Exception is HttpRequestValidationException)
            {
                filterContext.Result = View("InvalidInput");
                filterContext.ExceptionHandled = true;
            }

            base.OnException(filterContext);
        }

        protected User MembershipUser
        {
            get { return MembershipService.GetUser(true); }
        }

        protected void ClearCacheEntry(string cacheKey)
        {
            Cache.Remove(cacheKey);
        }

        protected ISpecification<TEntity> AddUserFilter<TEntity>(IFilterable<TEntity> filterable, ISpecification<TEntity> specification)
            where TEntity : Entity
        {
            var currentUser = MembershipUser;

            return filterable.GetFilterBuilder().BuildUserFilter(specification, currentUser.UserAccount);
        }

        /// <summary>
        /// return an byte array of a given file
        /// </summary>
        /// <param name="fileDocument">posted file</param>
        /// <returns></returns>
        private byte[] GetFileStream(HttpPostedFileBase fileDocument)
        {
            var buffer = new byte[fileDocument.ContentLength];

            fileDocument.InputStream.Read(buffer, 0, buffer.Length);

            return buffer;

        }


        /// <summary>
        /// return Base64String of a given file
        /// </summary>
        /// <param name="imageFile">posted file</param>
        /// <returns></returns>
        private string GetBaseImage(HttpPostedFileBase imageFile)
        {
            var buffer = new byte[imageFile.ContentLength];

            imageFile.InputStream.Read(buffer, 0, buffer.Length);

            return Convert.ToBase64String(buffer);

        }

        

        public JsonResult UploadNonMsieFiles()
        {
            try
            {
                var fileName = Request.Headers["X-File-Name"];

                var directoryPath = Server.MapPath("~/Upload/");

                if (!Directory.Exists(directoryPath))
                {
                    Directory.CreateDirectory(directoryPath);
                }

                var uploadedFilePath = string.Format("{0}{1}", directoryPath, fileName);

                Request.SaveAs(uploadedFilePath, false);

                return Json(fileName, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Response.StatusDescription = e.Message;
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public static byte[] StreamToByteArray(Stream input)
        {
            var buffer = new byte[16 * 1024];
            using (var ms = new MemoryStream())
            {
                int read;
                while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }
                return ms.ToArray();
            }
        }
    }
}

MIMS/Views/Shared/FileUploadMsie.cshtml
@using AlfasiWeb.Helpers
@using AlfasiWeb.Models
@model FileUploadModel

@{
    if(Model != null)
    {
        @Html.HiddenFor(m => m.ProjectUid, new { id = "hiddenProjectUid" })

        @Html.HiddenFor(m => m.FileName, new { id = "hiddenFileName" })
        @Html.HiddenFor(m => m.FileSize, new { id = "hiddenFileSize" })
        @Html.HiddenFor(m => m.Status, new { id = "hiddenStatus" })
        @Html.HiddenFor(m => m.UploadFilePath, new { id = "hiddenUploadFilePath" })
    }
}
   
<div id="group_table" class="login_bk">
    @{
        ViewBag.Title = "Mark List";
    }
    @Html.Message()
    <div class="content-bk">
        <div id="form_head">
            <h3>Tekla File Upload(IE)</h3>
        </div>
        <br />

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="Uploader">
                    <div class="Contaier-upload">
                        <div class="head_upload">
                            <div class="headings">
                                <h4 class="pull-left">
                                    File Uploader</h4>
                                <h6 class="pull-right">
                                    Drag and drop files here</h6>
                            </div>
                        </div>

                        <table class="table">
                            <tbody class="table_head">
                                <tr>
                                    <td class="span10">
                                        FileName
                                    </td>
                                    <td class="span2 ">
                                        <span>Size</span>
                                    </td>
                                    <td class="span2 ">
                                        <span>Status</span>
                                    </td>
                                    <td class="span1 ">
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <div id="dragandrophandler" >
                            <table id="uploadfilelist" class="table">
                                <tbody class="content_area">

                                </tbody>
                            </table>
                        </div>

                        <form action="@Url.Action("UploadMsieFiles", "Base")" method="POST" enctype="multipart/form-data" id="TeklaIE">
                            <div class="upload_filelist_footer">
                                <div class="upload_file_foooter_list">
                                    <div class="Buton_area">
                                            
                                        <input type="file" accept="image/*" name="fileIeUpload" id="fileIeUpload" style='visibility: hidden;' onchange="fileSelected();"/>
                                        <input type = "button" value = "Select File" onclick ="javascript:document.getElementById('fileIeUpload').click();" />

                                        <button class="btn btn-small" type="submit" id="buttonUpload" disabled="disabled" id="buttonUpload">
                                            <i class="icon-upload" ></i>Upload</button>
                                        <button class="btn btn-small" type="button" id="buttonSave" disabled="disabled">
                                            Save</button>

                                    </div>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var filequeue = new Array();
    var count = 0;

    var processedFileName;
    var processedFileSize;
    var processedStatus;
    var processedUploadedFilePath;

    $(document).ready(function () {

        processedFileName = $('#hiddenFileName').val();
        processedFileSize = $('#hiddenFileSize').val();
        processedStatus = $('#hiddenStatus').val();
        processedUploadedFilePath = $('#hiddenUploadFilePath').val();

        if (processedFileName != "") {

            var tr = document.createElement("tr");

            var tdFileName = document.createElement("td");
            tdFileName.setAttribute("class", "span11");
            tdFileName.innerHTML = processedFileName;
            tr.appendChild(tdFileName);

            var tdFileSize = document.createElement("td");
            tdFileSize.setAttribute("class", "span2");
            tdFileSize.innerHTML = processedFileSize;
            tr.appendChild(tdFileSize);

            var tdFileProgress = document.createElement("td");
            tdFileProgress.setAttribute("class", "span2");
            tdFileProgress.innerHTML = processedStatus;
            tr.appendChild(tdFileProgress);

            var tdFileRemove = document.createElement("td");
            tdFileRemove.setAttribute("class", "span1");
            tr.appendChild(tdFileRemove);

            $("#uploadfilelist tbody").append(tr);
        }


    });

    function fileTypeValidate(file, fileType) {

        var theFileType = null;
        var array = file.name.split('.');
        if (array.length > 1) {
            theFileType = array[1];
        }

        if (theFileType.match(fileType)) {
            return true;
        }
        return false;
    }

    function fileProgressDisplay(processingfiles) {

        var processingfileuniquekey = "F00" + count + "_";
        var processingfile = processingfiles[0];

        var tr = document.createElement("tr");

        var tdFileName = document.createElement("td");
        tdFileName.setAttribute("class", "span11");
        tdFileName.innerHTML = processingfileuniquekey + processingfile.name;
        tr.appendChild(tdFileName);

        var tdFileSize = document.createElement("td");
        tdFileSize.setAttribute("class", "span2");
        tdFileSize.innerHTML = processingfile.size;
        tr.appendChild(tdFileSize);

        var tdFileProgress = document.createElement("td");
        tdFileProgress.setAttribute("class", "span2");
        tdFileProgress.innerHTML = "0%";
        tr.appendChild(tdFileProgress);

        var tdFileRemove = document.createElement("td");
        tdFileRemove.setAttribute("class", "span1");
        var removeImg = document.createElement("img");
        removeImg.setAttribute("src", '@Url.Content("~/Content/fileupload/file-remove.png")');
        removeImg.setAttribute("onclick", "removeFile('" + processingfileuniquekey + "');");
        removeImg.setAttribute("height", "24");
        removeImg.setAttribute("width", "24");
        tdFileRemove.appendChild(removeImg);
        tr.appendChild(tdFileRemove);

        $("#uploadfilelist tbody").append(tr);

        var map = new Array(processingfile, processingfileuniquekey);
        filequeue.push({ file: map, tr: tr });

        count = count + 1;

        $("#buttonUpload").prop('disabled', false);
    }

    function fileSelected() {

        try {

            var files = document.getElementById('fileIeUpload').files;
            fileProgressDisplay(files);

            $("#fileToUpload").val("");

        } catch (err) {
            alert("Exception " + err);
        }
    }

    function removeImage(processingfileuniquekey) {

        try {

            $("#uploadfilelist tr").each(function () {

                if ($(this).find("td").eq(0).text().indexOf(processingfileuniquekey) != -1) {

                    var containtext = $(this).find("td").eq(0).text();

                    $(this).remove();

                    for (var b = 0; b < filequeue.length; b++) {

                        var processarray = filequeue[b];
                        var processmap = processarray.file;

                        if (containtext.indexOf(processmap[1]) != -1) {

                            filequeue.splice(b, 1);

                            break;
                        }
                    }

                }


            });


        } catch (err) {
            alert("Exception " + err);
        }
    }
	</script>

MIMS/Views/Shared/FileUploadNonMsie.cshtml
@using AlfasiWeb.Helpers
<div id="group_table" class="login_bk">
    @{
        ViewBag.Title = "Mark List";
    }
    @Html.Message()
    <div class="content-bk">
        <div id="form_head">
            <h3>File Upload</h3>
        </div>
        <br />

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="Uploader">
                    <div class="Contaier-upload">
                        <div class="head_upload">
                            <div class="headings">
                                <h4 class="pull-left">
                                    File Uploader</h4>
                                <h6 class="pull-right">
                                    Drag and drop files here</h6>
                            </div>
                        </div>

                        <table class="table">
                            <tbody class="table_head">
                                <tr>
                                    <td class="span10">
                                        FileName
                                    </td>
                                    <td class="span2 ">
                                        <span>Size</span>
                                    </td>
                                    <td class="span2 ">
                                        <span>Status</span>
                                    </td>
                                    <td class="span1 ">
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <div id="dragandrophandler" >
                            <table id="uploadfilelist" class="table">
                                <tbody class="content_area">

                                </tbody>
                            </table>
                        </div>

                        <div class="upload_filelist_footer">
                            <div class="upload_file_foooter_list">
                                <div class="Buton_area">
                                        
                                    <input type="file" accept="image/*" name="fileNonIEUpload" id="fileNonIEUpload" style='visibility: hidden;' onchange="fileSelected();"/>
                                    <input type = "button" value = "Select File" onclick ="javascript:document.getElementById('fileNonIEUpload').click();"/>

                                    <button class="btn btn-small" type="button" id="buttonUpload" onclick="uploadFiles();">
                                        <i class="icon-upload" ></i>Upload</button>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var filequeue = new Array();
    var count = 0;
    var uploadedFilePath;

    $(document).ready(function() {

        var processingfileuniquekey;
        var obj = $("#dragandrophandler");

        obj.on('dragenter', function(e) {
            e.stopPropagation();
            e.preventDefault();
        });
        obj.on('dragover', function(e) {
            e.stopPropagation();
            e.preventDefault();
        });
        obj.on('drop', function(e) {

            e.preventDefault();
            var files = e.originalEvent.dataTransfer.files;
            fileProgressDisplay(files);

        });
        $(document).on('dragenter', function (e) {
            e.stopPropagation();
            e.preventDefault();
        });
        $(document).on('dragover', function (e) {
            e.stopPropagation();
            e.preventDefault();
        });
        $(document).on('drop', function (e) {
            e.stopPropagation();
            e.preventDefault();
        });

    });

    function fileProgressDisplay(processingfiles) {

        var processingfileuniquekey = "F00" + count + "_";
        var processingfile = processingfiles[0];

        var tr = document.createElement("tr");

        var tdFileName = document.createElement("td");
        tdFileName.setAttribute("class", "span11");
        tdFileName.innerHTML = processingfileuniquekey + processingfile.name;
        tr.appendChild(tdFileName);

        var tdFileSize = document.createElement("td");
        tdFileSize.setAttribute("class", "span2");
        tdFileSize.innerHTML = processingfile.size;
        tr.appendChild(tdFileSize);

        var tdFileProgress = document.createElement("td");
        tdFileProgress.setAttribute("class", "span2");
        tdFileProgress.innerHTML = "0%";
        tr.appendChild(tdFileProgress);

        var tdFileRemove = document.createElement("td");
        tdFileRemove.setAttribute("class", "span1");
        var removeImg = document.createElement("img");
        removeImg.setAttribute("src", '@Url.Content("~/Content/fileupload/file-remove.png")');
        removeImg.setAttribute("onclick", "removeFile('" + processingfileuniquekey + "');");
        removeImg.setAttribute("height", "24");
        removeImg.setAttribute("width", "24");
        tdFileRemove.appendChild(removeImg);
        tr.appendChild(tdFileRemove);

        $("#uploadfilelist tbody").append(tr);

        var map = new Array(processingfile, processingfileuniquekey);
        filequeue.push({ file: map, tr: tr });

        count = count + 1;
    }

    function fileTypeValidate(file, fileType) {

        var theFileType = null;
        var array = file.name.split('.');
        if (array.length > 1) {
            theFileType = array[1];
        }

        if (theFileType.match(fileType)) {
            return true;
        }
        return false;
    }

    function fileSelected() {

        try {

            var files = document.getElementById('fileNonIEUpload').files;
            fileProgressDisplay(files);

            $("#fileToUpload").val("");

        } catch (err) {
            alert("FileSelected Exception " + err);
        }
    }

    function removeFile(processingfileuniquekey) {

        try {

            $("#uploadfilelist tr").each(function () {

                if ($(this).find("td").eq(0).text().indexOf(processingfileuniquekey) != -1) {

                    var containtext = $(this).find("td").eq(0).text();

                    $(this).remove();

                    for (var b = 0; b < filequeue.length; b++) {

                        var processarray = filequeue[b];
                        var processmap = processarray.file;

                        if (containtext.indexOf(processmap[1]) != -1) {

                            filequeue.splice(b, 1);

                            break;
                        }
                    }

                }


            });


        } catch (err) {
            alert("RemoveFile Exception " + err);
        }
    }

    function uploadFiles() {

        try {


            if (filequeue != null && filequeue.length != 0) {

                while (filequeue.length > 0) {

                    var item = filequeue.pop();
                    var processarray = item.file;
                    var file = processarray[0];
                    var key = processarray[1];

                    upload(file, key, item);

                }
            }

        } catch (err) {
            alert("UploadFiles Exception " + err);
        }

    }

    function GUID() {
        var S4 = function () {
            return Math.floor(
                Math.random() * 0x10000 /* 65536 */
            ).toString(16);
        };

        return (
            S4() + S4() + "-" +
                S4() + "-" +
                    S4() + "-" +
                        S4() + "-" +
                            S4() + S4() + S4()
        );
    }

    function upload(file, key, item) {

        try {

            var uploadurl = '@Url.Action("UploadNonMsieFiles", "Base")';
            uploadurl += "?bustCache=" + GUID();

            var tr = item.tr;
            var statusTd = $(tr).find('td').eq(2);

            var xhr = new XMLHttpRequest(), upload = xhr.upload;

            upload.addEventListener("loadstart", function (ev) {


            }, false);

            upload.addEventListener("progress", function (ev) {

                if (ev.lengthComputable) {

                    var percentComplete = Math.round(ev.loaded * 100 / ev.total);
                    statusTd.text(percentComplete + "%");
                    statusTd.css("color", "#3DD13F");
                }

            }, false);
            upload.addEventListener("load", function (evt) {

                statusTd.css("color", "#3DD13F");

            }, false);
            upload.addEventListener("error", function (ev) {

                if (xhr.status != 500) {

                    filequeue.push(item);

                    var containtext = statusTd.text();
                    statusTd.text(containtext + " upload error");
                    statusTd.css("color", "#FF0000");

                }

            }, false);

            xhr.open("POST", uploadurl);

            xhr.setRequestHeader("Content-type", "multipart/form-data");
            xhr.setRequestHeader("X-File-Name", (key + file.name));
            xhr.setRequestHeader("Cache-Control", "no-cache");
            xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
            xhr.setRequestHeader("X-File-Size", file.size);
            xhr.setRequestHeader("X-File-Type", file.type);


            xhr.send(file);

            xhr.onreadystatechange = function () {

                if (xhr.readyState != 4) {
                    return;
                } else if (xhr.readyState == 4) {

                    if (xhr.status == 500) {

                        var resp = JSON.parse(xhr.responseText);

                    } else if (xhr.status == 200) {
                        var jsonResponse = JSON.parse(xhr.responseText);
                        uploadedFilePath = jsonResponse;
                        $("#buttonSave").prop('disabled', false);
                        $(tr).fadeOut(5000);
                    }


                }

            };
        } catch (err) {
            alert("Upload Exception " + err);
        }
    }
    
</script>

MIMS/Views/Shared/InvalidInput.cshtml
@{
    ViewBag.Title = "InvalidInput";
}

<h2>Invalid input character/s please try again.</h2>

MIMS/Views/Shared/_LayoutLogin.cshtml
@using MIMS.Helpers
@{
    LoginMenuBuilder.Setup();
    ViewBag.VersionNumber = typeof(MIMS.MvcApplication).Assembly.GetName().Version;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/Bootstrap")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/qtip")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="body_bkk">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div id="header" style="margin-top:20px">
                        <div class="navbar">
                            <div class="container-narrow">
                                <a href="#">
                                    <div class="group">
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    @RenderBody()
                    <div id="footer">
                        <span class="vertion pull-left" style="margin-left: 20px;">ABC Solutions</span>
                        <span class="vertion pull-right">Version: 1.0000.1.0000</span>
                    </div>
                    <a href="#wrapper" class="hidden">Back to top</a>
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/Bootstrap")
    @Scripts.Render("~/bundles/DatePicker")
    @Scripts.Render("~/bundles/Util")
    <script src="@Url.Content("~/Scripts/custom/qtip/jquery.qtip.min.js")" type="text/javascript"></script>
    @Scripts.Render("~/bundles/TableSorter")
    <!--Bootstrap configuration requirement for IE8-->
    <script src="@Url.Content("~/Scripts/custom/bootstrap/respond.min.js")" type="text/javascript"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

MIMS/Views/Shared/_gridLinks.cshtml
@using AlfasiWeb.Helpers
@Html.GridLinks((object)Model)
@Ajax.BoostrapedDeletePopUpActionLink((object)Model)

MIMS/Views/Shared/_gridLinksMini.cshtml
@using AlfasiWeb.Helpers
@Ajax.BoostrapedDeletePopUpActionLink((object)Model)