MIMS/Controllers/SetMenuController.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web.Mvc;
using MIMS.Helpers;
using MIMS.Security;
using Dinota.Core.Data;
using Dinota.Domain;
using Dinota.Domain.User;
using Dinota.Core.Specification;
using Dinota.Security;
using System;
using AlfasiWeb.Models;
using Dinota.Domain.Division;
using Dinota.Domain.UserType;
using Dinota.Domain.District;
using Dinota.Domain.SLAFLocation;
using Dinota.Domain.FuelType;
using Dinota.Domain.RoomInfo;
using Dinota.Domain.RoomNo;
using Dinota.Domain.IngredientInfo;
using Dinota.Domain.MeasurementUnit;
using Dinota.Domain.IngredientBOC;
using Dinota.Domain.BOCTransaction;
using Dinota.Domain.StockSheetTransaction;
using Dinota.Domain.F140Header;
using Dinota.Domain.F140Data;
using Dinota.Domain.SetMenuHeader;
using Dinota.Domain.SetMenuDetail;
using Dinota.Domain.MenuItem;


namespace MIMS.Controllers
{
    //[Authorize]
   // [ExternalUserRedirectAttribute]
    public class SetMenuController : BaseController
    {
        private readonly UserAccountService _userAccountService;
        private readonly DivisionService _divisionService;
        private readonly UserTypeService _userTypeService;
        private readonly DistrictService _districtService;
        private readonly SLAFLocationService _SLAFLocationService;
        private readonly FuelTypeService _fuelTypeService;
        private readonly RoomInfoService _roomInfoService;
        private readonly RoomNoService _roomNoService;
        private readonly IngredientInfoService _ingredientInfoService;
        private readonly MeasurementUnitService _measurementUnitService;
        private readonly IngredientBOCService _ingredientBOCService;
        private readonly BOCTransactionService _bOCTransactionService;
        private readonly StockSheetTransactionService _stockSheetTransactionService;
        private readonly F140HeaderService _f140HeaderService;
        private readonly F140DataService _f140DataService;
        private readonly SetMenuHeaderService _setMenuHeaderService;
        private readonly SetMenuDetailService _setMenuDetailService;
        private readonly MenuItemService _menuItemService;


        public SetMenuController(IDomainContext dataContext, SetMenuDetailService setMenuDetailService, 
            SetMenuHeaderService setMenuHeaderService, F140DataService f140DataService, F140HeaderService f140HeaderService, 
            StockSheetTransactionService stockSheetTransactionService, BOCTransactionService bOCTransactionService, 
            IngredientBOCService ingredientBOCService, MeasurementUnitService measurementUnitService, IngredientInfoService ingredientInfoService, 
            UserAccountService userAccountService, RoomNoService roomNoService, RoomInfoService roomInfoService, 
            SLAFLocationService SLAFLocationService, FuelTypeService fuelTypeService, DistrictService districtService, 
            UserTypeService userTypeService, DivisionService divisionService, MenuItemService menuItemService)
            : base(dataContext)
        {
            _divisionService = divisionService;
            _userTypeService = userTypeService;
            _districtService = districtService;
            _fuelTypeService = fuelTypeService;
            _SLAFLocationService = SLAFLocationService;
            _roomInfoService = roomInfoService;
            _roomNoService = roomNoService;
            _userAccountService = userAccountService;
            _ingredientInfoService = ingredientInfoService;
            _measurementUnitService = measurementUnitService;
            _ingredientBOCService = ingredientBOCService;
            _bOCTransactionService = bOCTransactionService;
            _stockSheetTransactionService = stockSheetTransactionService;
            _f140HeaderService = f140HeaderService;
            _f140DataService = f140DataService;
            _setMenuHeaderService = setMenuHeaderService;
            _setMenuDetailService = setMenuDetailService;
            _menuItemService = menuItemService;
        }
        // [AuthorizeUserAccessLevel()]



        public void BindMeasurementList()
        {
            try
            {
                var filter = _measurementUnitService.GetDefaultSpecification().And(s => s.Active == true);
                var TypeList = _measurementUnitService.GetCollection(filter, d => d.UId);
                SelectList list = new SelectList(TypeList, "UId", "Unit");
                ViewData[ViewDataKeys.MeasurementUnitListList] = list;
            }
            catch (Exception ex)
            {
                TempData[ViewDataKeys.Message] = new FailMessage(ex.Message.ToString());

            }

        }
        public void BindItemList()
        {
            try
            {
                var filter = _ingredientInfoService.GetDefaultSpecification().And(s => s.Active == true);
                var TypeList = _ingredientInfoService.GetCollection(filter, d => d.UId);
                SelectList list = new SelectList(TypeList, "UId", "ItemName");
                ViewData[ViewDataKeys.IngredientInfoList] = list;
            }
            catch (Exception ex)
            {
                TempData[ViewDataKeys.Message] = new FailMessage(ex.Message.ToString());

            }

        }
       
        public ActionResult SetMenuEdit(int id)
        {
            SetMenuHeader oSetMenuHeader = new SetMenuHeader();
            oSetMenuHeader = _setMenuHeaderService.GetByKey(id);
            try
            {
                oSetMenuHeader = _setMenuHeaderService.GetByKey(id);
                
            }
            catch (Exception)
            {

                throw;
            }
            return View(oSetMenuHeader);
        }
       
        [HttpPost]
        public ActionResult SetMenuEdit(FormCollection Form,int id)
        {
            SetMenuHeader oSetMenuHeader = new SetMenuHeader();

            try
            {
                TryUpdateModel(oSetMenuHeader);
                BindMeasurementList();

                oSetMenuHeader = _setMenuHeaderService.GetByKey(id);
                DataContext.SaveChanges();
                TempData[ViewDataKeys.Message] = new SuccessMessage("Successfully Saved");
                return RedirectToAction("SetMenuList");
                
            }
            catch (Exception)
            {

                throw;
            }
            
        }
        public ActionResult SetMenuRegister()
        {
            SetMenuHeader oSetMenuHeader = new SetMenuHeader();
            try
            {
                TryUpdateModel(oSetMenuHeader);
                //info.Active = true;
            }
            catch (Exception)
            {

                throw;
            }
            return View(oSetMenuHeader);
        }
        [HttpPost]
        public ActionResult SetMenuRegister(FormCollection Form)
        {
            SetMenuHeader oSetMenuHeader = new SetMenuHeader();
            try
            {
                TryUpdateModel(oSetMenuHeader);
                UserAccount account = GetCurrentUser();
           
                oSetMenuHeader.Active = true;
                oSetMenuHeader.LocationUId = account.LocationUId;
                _setMenuHeaderService.Add(oSetMenuHeader);
                DataContext.SaveChanges();
                TempData[ViewDataKeys.Message] = new SuccessMessage("Successfully Saved");
                return RedirectToAction("SetMenuList");
                
                
            }
            catch (Exception)
            {

                throw;
            }
            
        }

        public ActionResult SetMenuPackageList(int id)
        {
            SetMenuModel model = new SetMenuModel();
            try
            {
                UserAccount account = GetCurrentUser();
                var filter = _menuItemService.GetDefaultSpecification();
                filter = filter.And(p => p.Active == true).And(p => p.SLAFLocationUId == account.LocationUId);
                List<MenuItem> MenuitemList = _menuItemService.GetCollection(filter, p => p.CreationDate).ToList();
                model.MenuItemList = MenuitemList;

                var filterM = _setMenuDetailService.GetDefaultSpecification();
                filterM = filterM.And(p => p.Active == true).And(p => p.SetMenuHeaderId == id);
                List<SetMenuDetail> MenuPackageList = _setMenuDetailService.GetCollection(filterM, p => p.CreationDate).ToList();
                model.SetMenuDetailList = MenuPackageList;
                model.MenuItemId = id;

                SetMenuHeader item = _setMenuHeaderService.GetByKey(id);
                TempData["MenuItem"] = item.SetMenuName;
                TempData["MenuItemId"] = item.UId;

            }
            catch (Exception)
            {

                throw;
            }
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult AddPackageSetMenu(int MenuId, int MenuItemId)
        {
            try
            {
                UserAccount account = GetCurrentUser();
                SetMenuDetail package = new SetMenuDetail();

                package.MenuItemId = MenuId;
                package.SetMenuHeaderId = MenuItemId;
                package.LocationUId = account.LocationUId;
                package.Active = true;
                _setMenuDetailService.Add(package);
                DataContext.SaveChanges();
                TempData[ViewDataKeys.Message] = new SuccessMessage("Menu Updated.");
                return RedirectToAction("SetMenuPackageList", new { id = MenuItemId });
            }
            catch (Exception)
            {

                throw;
            }
            return View();
        }

        public ActionResult RemovePackageSetMenu(int id)
        {
            try
            {
                SetMenuDetail package = _setMenuDetailService.GetByKey(id);
                package.Active = false;

MIMS/Views/SetMenu/SetMenuEdit.cshtml
@using MIMS
@using MIMS.Helpers
@using Dinota.Security
@using Dinota.Domain.SetMenuHeader
@using Dinota.Domain.Event
@using AlfasiWeb.Models
@model SetMenuHeader
@{
    ViewBag.Title = "MenuItemRegister";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-none">
    <div class="bg-primary border-bottom p-3 d-flex align-items-center">
        <a class="toggle togglew toggle-2" href="#"><span></span></a>
        <h4 class="font-weight-bold m-0 text-white">Edit SetMenu Item</h4>
    </div>
</div>
<div class="container position-relative">
    <div class="py-5 osahan-profile row">

        <div class="col-md-12 mb-3">
            <div class="rounded shadow-sm p-4 bg-white">
                <h5 class="mb-4">Edit Menu Item</h5>
                <div id="edit_profile">
                    <div>
                        @Html.Message()
                        @using (Html.BeginForm("SetMenuEdit", "SetMenu", new { id=Model.UId}, FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
                        {
                            @Html.Partial("_CreateEditMenu", Model)
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

MIMS/Views/SetMenu/SetMenuList.cshtml
@using MIMS
@using MIMS.Helpers
@using Dinota.Security
@using Dinota.Domain.SetMenuHeader
@using AlfasiWeb.Models
@model List<SetMenuHeader>
@{
    ViewBag.Title = "SetMenuList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="d-none">
    <div class="bg-primary border-bottom p-3 d-flex align-items-center">
        <a class="toggle togglew toggle-2" href="#"><span></span></a>
        <h4 class="font-weight-bold m-0 text-white">Set Menu List</h4>
    </div>
</div>
<div class="container position-relative">

    <div class="py-5 osahan-profile row">

        <center><h4>Set Menu List</h4></center>

        <div class="col-md-12 mb-3">
            <a href="@Url.Content("~/SetMenu/SetMenuRegister/")" class="btn btn-primary px-3 " style="float:right">Add New Set Menu</a>
            <div class="clearfix"></div>
            @Html.Message()
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Set Menu Name</th>
                        <th></th>

                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (SetMenuHeader ord in Model)
                    {
                        <tr>
                            <td>
                                @ord.SetMenuName
                            </td>

                            <td><a href="@Url.Content("~/SetMenu/SetMenuPackageList/")@ord.UId" class="btn btn-primary px-3">Set Menu Package</a></td>
                            @*<td>@ord.MenuItemId</td>
                            <td>@ord.MeasurementUnit.Unit</td>
                            <td><a href="@Url.Content("~/Menu/IngriedientList/")@ord.UId" class="btn btn-primary px-3">Ingredients List</a></td>
                            <td>
                                @if (ord.IsCombine)
                                {
                                    <a href="@Url.Content("~/Menu/PackageList/")@ord.UId" class="btn btn-primary px-3">Package List</a>
                                }
                            </td>*@
                            <td><a href="@Url.Content("~/SetMenu/SetMenuEdit/")@ord.UId" class="btn btn-primary px-3">Edit</a></td>

                        </tr>
                    }
                </tbody>
            </table>




        </div>
    </div>

</div>
<script src="~/Asset/js/jquery-3.5.1.js"></script>
<script src="~/Asset/js/jquery.dataTables.min.js"></script>
<script src="~/Asset/js/dataTables.bootstrap4.min.js"></script>
<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

MIMS/Views/SetMenu/SetMenuPackageList.cshtml
@using MIMS
@using MIMS.Helpers
@using Dinota.Security
@using Dinota.Domain.User
@using Dinota.Domain.MenuItem
@using Dinota.Domain.SetMenuDetail
@using AlfasiWeb.Models
@model SetMenuModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="d-none">
    <div class="bg-primary border-bottom p-3 d-flex align-items-center">
        <a class="toggle togglew toggle-2" href="#"><span></span></a>
        <h4 class="font-weight-bold m-0 text-white">Set Menu Package Edit</h4>
    </div>
</div>
<div class="container position-relative">
    <div class="py-5 osahan-profile row">

        <div class="col-md-12 mb-3">
            <p style="font-size:16px;"><b>Set Menu Name : </b>@TempData["MenuItem"]</p>
                <table class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Menu Item</th>
                            <th>Unit</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (SetMenuDetail det in Model.SetMenuDetailList)
                        {
                            <tr>
                                <td>@det.MenuItem.Name</td>
                                
                                <td>@det.MenuItem.MeasurementUnit.Unit</td>
                                <td><a href="@Url.Content("~/SetMenu/RemovePackageSetMenu/")@det.UId" class="btn btn-primary px-3">
                                        <img src="~/Asset/img/remove.png" width="25px"/></a></td>
                            </tr>
                        }
                    </tbody>
                </table>

                <div class="text-center">
                   
                   <br/><br />
                </div>
           
            @Html.Message()
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Category</th>
                        <th>Name</th>
                        <th>Measurement Unit</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (MenuItem info in Model.MenuItemList)
                    {
                        <tr>
                            <td>@info.MenuCategory.Name</td>
                            <td>@info.Name</td>
                            
                            <td>@info.MeasurementUnit.Unit</td>

                            <td><a href="@Url.Content("~/SetMenu/AddPackageSetMenu?MenuId="+info.UId+"&&MenuItemId="+Model.MenuItemId + "")" class="btn btn-primary px-3">Add Menu Item</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="~/Asset/js/jquery-3.5.1.js"></script>
<script src="~/Asset/js/jquery.dataTables.min.js"></script>
<script src="~/Asset/js/dataTables.bootstrap4.min.js"></script>
<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>

MIMS/Views/SetMenu/SetMenuRegister.cshtml
@using MIMS
@using MIMS.Helpers
@using Dinota.Security
@using Dinota.Domain.SetMenuHeader
@using AlfasiWeb.Models
@model SetMenuHeader
@{
    ViewBag.Title = "MenuItemRegister";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-none">
    <div class="bg-primary border-bottom p-3 d-flex align-items-center">
        <a class="toggle togglew toggle-2" href="#"><span></span></a>
        <h4 class="font-weight-bold m-0 text-white">Add Menu Item</h4>
    </div>
</div>
<div class="container position-relative">
    <div class="py-5 osahan-profile row">

        <div class="col-md-12 mb-3">
            <div class="rounded shadow-sm p-4 bg-white">
                <h5 class="mb-4">Add Menu Item</h5>
                <div id="edit_profile">
                    <div>
                        @Html.Message()
                        @using (Html.BeginForm("SetMenuRegister", "SetMenu", null, FormMethod.Post, new { @class = "form-horizontal", @enctype = "multipart/form-data" }))
                        {
                            @Html.Partial("_CreateEditMenu", Model)
                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

MIMS/Views/SetMenu/_CreateEditMenu.cshtml
@using MIMS
@using MIMS.Helpers
@using Dinota.Security
@using Dinota.Domain.SetMenuHeader
@using AlfasiWeb.Models
@model SetMenuHeader
@{
    ViewBag.Title = "_CreateEdit";
}

<div class="form-group">
    <label for="exampleInputName1">Set Menu Name</label>
    @Html.TextBoxFor(m => m.SetMenuName, new { @placeholder = "Enter Set Menu Name", @data_rule_required = "true", @data_rule_email = "true", @class = "form-control", @aria_required = "true", @Required = "true" })
    @Html.ValidationMessageFor(m => m.SetMenuName, "")
</div>
@*<div class="form-group">
        <label for="exampleInputName1">Portion Qty</label>
        @Html.TextBoxFor(m => m.PortionQty, new { @placeholder = "Enter portion Qty", @data_rule_required = "true", @data_rule_email = "true", @class = "form-control", @aria_required = "true", @Required = "true",@type="number" })
        @Html.ValidationMessageFor(m => m.PortionQty, "")
    </div>
    <div class="form-group">
        <label for="exampleInputName1">Select Measurement Unit</label>
        @Html.DropDownListFor(model => model.MeasurementUnitId, (IEnumerable<SelectListItem>)ViewData[MIMS.ViewDataKeys.MeasurementUnitListList], "-- Select Measure Unit  --", new { @class = "full-width form-control", @required = "true" })
        @Html.ValidationMessageFor(m => m.MeasurementUnitId, null, new { @class = "help-inline" })

    </div>
    <div class="form-group">
        <label for="exampleInputName1">Select Categorty</label>
        @Html.DropDownListFor(model => model.MenuCategoryUId, (IEnumerable<SelectListItem>)ViewData[MIMS.ViewDataKeys.MenuCategoryList], "-- Select Category  --", new { @class = "full-width form-control", @required = "true" })
        @Html.ValidationMessageFor(m => m.MenuCategoryUId, null, new { @class = "help-inline" })

    </div>*@

@if (Model.UId == 0)
{

    <div class="text-center">
        <button type="submit" class="btn btn-primary btn-block">Submit</button>
    </div>

}
else
{
    <div class="form-group">
        <label for="exampleInputName1">Active</label>
        @Html.CheckBoxFor(m => m.Active)
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-primary btn-block">Update</button>
    </div>
}